//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcEquipment
    {
        public string Barcode { get; set; }
        public int EquipmentID { get; set; }
        public string State { get; set; }
        public System.DateTime MaintenanceTime { get; set; }
        public string ProducingAreas { get; set; }
        public string ProductionDate { get; set; }
        public int SupplierID { get; set; }
        public string LinkMan { get; set; }
        public string LinkTel { get; set; }
        public int Department { get; set; }
        public int UserID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int OperatorID { get; set; }
        public string OperateTime { get; set; }
        public string Remark { get; set; }
        public byte[] C_T { get; set; }
        public int ProofID { get; set; }
        public int DepartmentID { get; set; }
        public string Batch { get; set; }
    }
}
