//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DcEquipment
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Mnemonic { get; set; }
        public int EquipmentTypeID { get; set; }
        public string Model { get; set; }
        public string Band { get; set; }
        public string Manufacturer { get; set; }
        public int MaintenanceCycle { get; set; }
        public int Warning { get; set; }
        public string Remark { get; set; }
        public bool Disable { get; set; }
        public bool del { get; set; }
        public byte[] C_T { get; set; }
    }
}
