//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DcOrganization
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Mnemonic { get; set; }
        public int AreaID { get; set; }
        public string OrganizationType { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string Contact { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string bank { get; set; }
        public string Account { get; set; }
        public string Tax { get; set; }
        public string LegalPerson { get; set; }
        public string RegisteredCapital { get; set; }
        public string Manager { get; set; }
        public string Remark { get; set; }
        public bool Disable { get; set; }
        public bool del { get; set; }
        public byte[] C_T { get; set; }
    }
}
