//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DcPersonnel
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Mnemonic { get; set; }
        public int OrganizationID { get; set; }
        public int DepartmentID { get; set; }
        public string Position { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string Remark { get; set; }
        public bool Disable { get; set; }
        public bool del { get; set; }
        public byte[] C_T { get; set; }
        public string Barcode { get; set; }
    }
}
