//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LGDataBaseEntities : DbContext
    {
        public LGDataBaseEntities()
            : base("name=LGDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcBucket> AcBucket { get; set; }
        public virtual DbSet<AcBucketRecord> AcBucketRecord { get; set; }
        public virtual DbSet<AcCheckBatch> AcCheckBatch { get; set; }
        public virtual DbSet<AcCheckItem> AcCheckItem { get; set; }
        public virtual DbSet<AcEquipment> AcEquipment { get; set; }
        public virtual DbSet<AcEquipmentManage> AcEquipmentManage { get; set; }
        public virtual DbSet<AcEquipmentManage_LS> AcEquipmentManage_LS { get; set; }
        public virtual DbSet<AcEquipmentRecord> AcEquipmentRecord { get; set; }
        public virtual DbSet<AcEquipmentRepair> AcEquipmentRepair { get; set; }
        public virtual DbSet<AcEquipmentRepair_LS> AcEquipmentRepair_LS { get; set; }
        public virtual DbSet<AcProduction> AcProduction { get; set; }
        public virtual DbSet<AcProductionRecord> AcProductionRecord { get; set; }
        public virtual DbSet<AcProof> AcProof { get; set; }
        public virtual DbSet<AcQueryRecord> AcQueryRecord { get; set; }
        public virtual DbSet<AcRepairParts> AcRepairParts { get; set; }
        public virtual DbSet<AcShift> AcShift { get; set; }
        public virtual DbSet<AcShiftPersonnel> AcShiftPersonnel { get; set; }
        public virtual DbSet<AcYield> AcYield { get; set; }
        public virtual DbSet<DcEquipment> DcEquipment { get; set; }
        public virtual DbSet<DcOrganization> DcOrganization { get; set; }
        public virtual DbSet<DcPersonnel> DcPersonnel { get; set; }
        public virtual DbSet<DcProduct> DcProduct { get; set; }
        public virtual DbSet<DcProductionLine> DcProductionLine { get; set; }
        public virtual DbSet<LiBucketState> LiBucketState { get; set; }
        public virtual DbSet<LiCheckState> LiCheckState { get; set; }
        public virtual DbSet<LiEquipmentState> LiEquipmentState { get; set; }
        public virtual DbSet<LiFaultyAddress> LiFaultyAddress { get; set; }
        public virtual DbSet<LiFaultyType> LiFaultyType { get; set; }
        public virtual DbSet<LiOrganizationType> LiOrganizationType { get; set; }
        public virtual DbSet<LiSamplingType> LiSamplingType { get; set; }
        public virtual DbSet<LiShift> LiShift { get; set; }
        public virtual DbSet<LiYesNo> LiYesNo { get; set; }
        public virtual DbSet<PfRawInBarcode> PfRawInBarcode { get; set; }
        public virtual DbSet<PfRawInDetail> PfRawInDetail { get; set; }
        public virtual DbSet<PfRawInHead> PfRawInHead { get; set; }
        public virtual DbSet<SbArea> SbArea { get; set; }
        public virtual DbSet<SbDepartment> SbDepartment { get; set; }
        public virtual DbSet<SbEquipment> SbEquipment { get; set; }
        public virtual DbSet<SbProduct> SbProduct { get; set; }
        public virtual DbSet<SbProductionLine> SbProductionLine { get; set; }
        public virtual DbSet<SyAuthorize> SyAuthorize { get; set; }
        public virtual DbSet<SyBarcodeTemplete> SyBarcodeTemplete { get; set; }
        public virtual DbSet<SyDefine> SyDefine { get; set; }
        public virtual DbSet<SyDefineGroup> SyDefineGroup { get; set; }
        public virtual DbSet<SyFiles> SyFiles { get; set; }
        public virtual DbSet<SyLog> SyLog { get; set; }
        public virtual DbSet<SyNumbers> SyNumbers { get; set; }
        public virtual DbSet<SyOptions> SyOptions { get; set; }
        public virtual DbSet<SyReport> SyReport { get; set; }
        public virtual DbSet<SyReportCheck> SyReportCheck { get; set; }
        public virtual DbSet<SyRole> SyRole { get; set; }
        public virtual DbSet<SyRoleRight> SyRoleRight { get; set; }
        public virtual DbSet<SyUser> SyUser { get; set; }
    }
}
