//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfRawInBarcode
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int DID { get; set; }
        public string BarcodeType { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public string ProducingAreas { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string Batch { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string Remark { get; set; }
        public byte[] C_T { get; set; }
    }
}
