//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfRawInHead
    {
        public int ID { get; set; }
        public string ProofCode { get; set; }
        public System.DateTime ProofDate { get; set; }
        public string ProofState { get; set; }
        public int OrgID { get; set; }
        public int OutsideOrgID { get; set; }
        public int OutsideManID { get; set; }
        public string Contact { get; set; }
        public string OutsideManTel { get; set; }
        public string OutsideManPhone { get; set; }
        public string Address { get; set; }
        public int BusinessManID { get; set; }
        public System.DateTime RawInDate { get; set; }
        public string LinkProofName { get; set; }
        public string LinkProofNo { get; set; }
        public int CreaterID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public int CheckerID { get; set; }
        public string Remark { get; set; }
        public byte[] C_T { get; set; }
    }
}
