//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyDefine
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int OrderKey { get; set; }
        public string FieldName { get; set; }
        public string Title { get; set; }
        public string Format { get; set; }
        public bool Visible { get; set; }
        public bool NotNull { get; set; }
        public int Width { get; set; }
        public string Alignment { get; set; }
        public byte[] C_T { get; set; }
    }
}
