//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyFiles
    {
        public int ID { get; set; }
        public string TableModelName { get; set; }
        public int PID { get; set; }
        public string SourceName { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public string Remark { get; set; }
        public int SubmitEmployeeID { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public byte[] C_T { get; set; }
    }
}
