//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyReport
    {
        public int ID { get; set; }
        public string ReportKey { get; set; }
        public string ReportName { get; set; }
        public byte[] ReportTemplate { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public bool Enable { get; set; }
        public int SubmittedID { get; set; }
        public bool Del { get; set; }
        public byte[] C_T { get; set; }
    }
}
